spring.application.name=Vayunetra

spring.data.mongodb.uri=mongodb+srv://PARV:Parv%4066@cluster0.gzbo5z1.mongodb.net/vayunetradb?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.database=vayunetradb

spring.data.mongodb.auto-index-creation=true

weather.api.url== "https://api.weatherstack.com/current?access_key=API_KEY&query=CITY";

weather.api.key=883ca67d1883407af060dae614cef303

